[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
textColor = "#31333F"
secondaryBackgroundColor = "#F0F2F6"
font = "monospace"
[
server
]
enableCORS = false
[
global
]
developmentMode = false